/**
 * generate.mjs — turns the editable sources (assets/parts/*.png +
 * assets/layout.json) into the committed modules the apps consume
 * (src/generated/sprites.ts + src/generated/layout.ts).
 *
 *   pnpm --filter @git-manager/mascot generate
 *
 * Run it whenever a part or the layout changes (the layout JSON is the
 * Storybook Layout editor's export — see README). The output is committed so
 * consumers (landing, desktop) need no image tooling in their builds.
 *
 * Unlike the old packed-sheet pipeline, each part is already its own
 * genuinely-transparent PNG (no chroma-key background to remove) — every
 * part file is a full-size export off the same master illustration canvas,
 * so a part's pixels sit at the same coordinates across every file (this is
 * what lets `assets/layout.json`'s placements be computed once from that
 * shared frame rather than hand-picked per zone; see the README). Pipeline
 * per part:
 *   1. trim to the bounding box of non-transparent pixels, padded by PAD px
 *      so anti-aliased edge pixels aren't clipped;
 *   2. encode as WebP (quality 82) and inline as a base64 data URI.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const PAD = 4;
const WEBP_QUALITY = 82;

const layout = JSON.parse(await readFile(join(pkgRoot, 'assets/layout.json'), 'utf8'));
if (layout.version !== 2) throw new Error(`layout.json: unsupported version ${layout.version}`);

async function slice(part) {
  const path = join(pkgRoot, 'assets/parts', part.file);
  const source = sharp(path);
  const { width: sw, height: sh } = await source.metadata();
  const { info } = await source.trim({ threshold: 10 }).toBuffer({ resolveWithObject: true });
  const left = Math.max(0, -info.trimOffsetLeft - PAD);
  const top = Math.max(0, -info.trimOffsetTop - PAD);
  const width = Math.min(sw - left, info.width + 2 * PAD);
  const height = Math.min(sh - top, info.height + 2 * PAD);
  const padded = await sharp(path)
    .extract({ left, top, width, height })
    .webp({ quality: WEBP_QUALITY })
    .toBuffer();
  const meta = await sharp(padded).metadata();
  return { id: part.id, w: meta.width, h: meta.height, uri: `data:image/webp;base64,${padded.toString('base64')}` };
}

const sprites = [];
for (const part of layout.parts) sprites.push(await slice(part));

const banner = `/**
 * GENERATED by scripts/generate.mjs from assets/parts/*.png + assets/layout.json —
 * do not edit by hand; run \`pnpm --filter @git-manager/mascot generate\`.
 */
`;

const spritesTs = `${banner}
export interface SpriteDef {
  uri: string;
  w: number;
  h: number;
}

export const SPRITES = {
${sprites.map((s) => `  ${s.id}: { uri: '${s.uri}', w: ${s.w}, h: ${s.h} },`).join('\n')}
} as const satisfies Record<string, SpriteDef>;
`;

const layoutTs = `${banner}
import { SPRITES, type SpriteDef } from './sprites';

export interface GeneratedPlacement {
  zone: keyof typeof SPRITES;
  role: string;
  sprite: SpriteDef;
  x: number;
  y: number;
  scale: number;
  rot: number;
  flip: boolean;
  opacity: number;
  pivot: { x: number; y: number };
  anim: { amp: number; dur: number; delay: number };
}

export const STAGE = { width: ${layout.stage.width}, height: ${layout.stage.height} } as const;

/** Paint order: first = furthest back, last = frontmost. */
export const PLACEMENTS: readonly GeneratedPlacement[] = [
${layout.placements
  .map((p) => {
    const role = layout.parts.find((z) => z.id === p.zone)?.role ?? 'other';
    return `  { zone: '${p.zone}', role: '${role}', sprite: SPRITES.${p.zone}, x: ${p.x}, y: ${p.y}, scale: ${p.scale}, rot: ${p.rot}, flip: ${p.flip}, opacity: ${p.opacity}, pivot: { x: ${p.pivot.x}, y: ${p.pivot.y} }, anim: { amp: ${p.anim.amp}, dur: ${p.anim.dur}, delay: ${p.anim.delay} } },`;
  })
  .join('\n')}
];
`;

await mkdir(join(pkgRoot, 'src/generated'), { recursive: true });
await writeFile(join(pkgRoot, 'src/generated/sprites.ts'), spritesTs);
await writeFile(join(pkgRoot, 'src/generated/layout.ts'), layoutTs);

const total = sprites.reduce((sum, s) => sum + s.uri.length, 0);
console.log(
  sprites.map((s) => `${s.id.padEnd(7)} ${s.w}x${s.h}`).join('\n') +
    `\n→ src/generated/{sprites,layout}.ts (${Math.round(total / 1024)}K base64)`,
);
