// Provider presets (the user-facing choice + its wire protocol)
export type { AiProtocol, AiPresetId, AiPresetDefinition } from './presets'
export { AI_PRESETS, getAiPreset, migrateAiPresetId } from './presets'

// Config / wire types
export type {
  AiConnectionConfig,
  AiProviderStatus,
  AiCheckConfig,
  AiGenerateConfig,
  AiContext,
  AiContextFile,
  AiContextScope,
  AiActivity,
  AiActivityCommit,
  AiActivityPending,
  CommitConvention,
  JsonSchema,
} from './config'

// Prompt sizing — surfaces context overflow, which every provider fails at silently.
export {
  estimateTokens,
  variableCharBudget,
  contextTokensFor,
  DEFAULT_CONTEXT_TOKENS,
} from './promptSize'

// The extensibility runtime: describe a feature once, wrap it into a typed service.
export type {
  AiFeature,
  StreamingFeature,
  CompletionFeature,
  AiTransport,
  StreamingFeatureService,
  CompletionFeatureService,
  AiStatusService,
  AiModelProbeResult,
} from './runtime'
export {
  resolveGenerateConfig,
  createStreamingService,
  createCompletionService,
  createStatusService,
  MODEL_PROBE_INSTRUCTION,
  MODEL_PROBE_PROMPT,
  MODEL_PROBE_MAX_TIMEOUT_SECONDS,
} from './runtime'

// Shipped features (one "service per feature" is assembled from these in the app's api layer).
export {
  commitMessageFeature,
  COMMIT_MESSAGE_INSTRUCTION,
  buildCommitUserPrompt,
  assessCommitMessageCoverage,
  detectScope,
  truncateDiff,
  fileGroupingFeature,
  FILE_GROUPING_INSTRUCTION,
  FILE_GROUPING_SCHEMA,
  buildGroupingUserPrompt,
  assessFileGroupingCoverage,
  parseCommitPlan,
  dailySummaryFeature,
  DAILY_SUMMARY_INSTRUCTION,
  DAILY_SUMMARY_SCHEMA,
  buildDailySummaryPrompt,
  parseDailySummary,
  prDescriptionFeature,
  PR_DESCRIPTION_INSTRUCTION,
  buildPrDescriptionUserPrompt,
  assessPrDescriptionCoverage,
  changeExplanationFeature,
  CHANGE_EXPLANATION_INSTRUCTION,
  buildChangeExplanationPrompt,
  assessChangeExplanationCoverage,
  branchExplanationFeature,
  BRANCH_EXPLANATION_INSTRUCTION,
  buildBranchExplanationPrompt,
  assessBranchExplanationCoverage,
  commitExplanationFeature,
  COMMIT_EXPLANATION_INSTRUCTION,
  buildCommitExplanationPrompt,
  assessCommitExplanationCoverage,
  workingExplanationFeature,
  WORKING_EXPLANATION_INSTRUCTION,
  buildWorkingExplanationPrompt,
  assessWorkingExplanationCoverage,
  codeReviewFeature,
  CODE_REVIEW_INSTRUCTION,
  buildCodeReviewPrompt,
  reviewDiffBudget,
  assessCodeReviewCoverage,
  languageName,
  budgetDiff,
  splitDiffByFile,
  classifyDiffPath,
  assessDiffCoverage,
  diffCharBudget,
  notIncludedSection,
  cappedList,
  DEFAULT_COMMIT_TYPES,
  parseCommitlintRules,
  isConventionalHistory,
  compilePattern,
  buildConventionSection,
  buildRecentCommitsSection,
  buildUserInstructionsSection,
  buildCommitStyleSection,
  validateCommitSubject,
} from './features'
export type {
  ProposedCommit,
  FileGroupingInput,
  CommitMessageInput,
  DailySummary,
  PrDescriptionInput,
  ChangeExplanationInput,
  ChangeExplanationFile,
  BranchExplanationInput,
  CommitExplanationInput,
  CommitExplanationCommit,
  CommitExplanationFile,
  WorkingExplanationInput,
  CodeReviewInput,
  CodeReviewScope,
  CodeReviewCoverage,
  BudgetedDiff,
  DiffFileSection,
  DiffFileTier,
  DiffCoverage,
  DiffPromptSizing,
  CommitlintRules,
  CommitStyleContext,
  CommitValidation,
  CommitValidationProblem,
} from './features'
