// Provider presets (the user-facing choice + its wire protocol)
export type { AiProtocol, AiPresetId, AiPresetDefinition } from './presets'
export { AI_PRESETS, getAiPreset, migrateAiPresetId } from './presets'

// Config / wire types
export type {
  AiConnectionConfig,
  AiProviderStatus,
  AiCheckConfig,
  AiGenerateConfig,
  AiContext,
  AiContextFile,
  AiContextScope,
  AiActivity,
  AiActivityCommit,
  AiActivityPending,
  CommitConvention,
  JsonSchema,
} from './config'

// Prompt sizing — surfaces context overflow, which every provider fails at silently.
export {
  estimateTokens,
  variableCharBudget,
  contextTokensFor,
  DEFAULT_CONTEXT_TOKENS,
  RESERVED_OUTPUT_TOKENS,
} from './promptSize'

// The extensibility runtime: describe a feature once, wrap it into a typed service.
export type {
  AiFeature,
  StreamingFeature,
  CompletionFeature,
  AiTransport,
  StreamingFeatureService,
  CompletionFeatureService,
  AiStatusService,
  AiModelProbeResult,
} from './runtime'
export {
  resolveGenerateConfig,
  createStreamingService,
  createCompletionService,
  createStatusService,
  MODEL_PROBE_INSTRUCTION,
  MODEL_PROBE_PROMPT,
  MODEL_PROBE_MAX_TIMEOUT_SECONDS,
  MODEL_PROBE_MAX_OUTPUT_TOKENS,
} from './runtime'

// Shipped features (one "service per feature" is assembled from these in the app's api layer).
export {
  COMMIT_MESSAGE_INSTRUCTION,
  COMMIT_MESSAGE_SCHEMA,
  detectScope,
  truncateDiff,
  parseCommitMessage,
  formatCommitMessage,
  FILE_GROUPING_SCHEMA,
  groupingOutputTokens,
  fileSummaryFeature,
  FILE_SUMMARY_INSTRUCTION,
  FILE_SUMMARY_SCHEMA,
  FILE_SUMMARY_OUTPUT_TOKENS,
  buildFileSummaryPrompt,
  parseFileSummary,
  summaryGroupingFeature,
  SUMMARY_GROUPING_INSTRUCTION,
  buildSummaryGroupingPrompt,
  summaryGroupingOutputTokens,
  renderSummaryList,
  summarizeFiles,
  SummaryRunCancelled,
  planCommitsFromSummaries,
  summaryCommitMessageFeature,
  SUMMARY_COMMIT_MESSAGE_INSTRUCTION,
  buildSummaryCommitMessagePrompt,
  composeCommitMessageFromSummaries,
  commitRecomposeFeature,
  COMMIT_RECOMPOSE_INSTRUCTION,
  buildCommitRecomposePrompt,
  assessCommitRecomposeCoverage,
  parseRecomposedMessage,
  parseCommitPlan,
  dailySummaryFeature,
  DAILY_SUMMARY_INSTRUCTION,
  DAILY_SUMMARY_SCHEMA,
  buildDailySummaryPrompt,
  parseDailySummary,
  summaryPrDescriptionFeature,
  SUMMARY_PR_DESCRIPTION_INSTRUCTION,
  buildSummaryPrDescriptionPrompt,
  changeExplanationFeature,
  CHANGE_EXPLANATION_INSTRUCTION,
  buildChangeExplanationPrompt,
  assessChangeExplanationCoverage,
  summaryExplanationFeature,
  SUMMARY_EXPLANATION_INSTRUCTION,
  buildSummaryExplanationPrompt,
  codeReviewFeature,
  CODE_REVIEW_INSTRUCTION,
  buildCodeReviewPrompt,
  reviewDiffBudget,
  assessCodeReviewCoverage,
  languageName,
  budgetDiff,
  splitDiffByFile,
  classifyDiffPath,
  assessDiffCoverage,
  diffCharBudget,
  notIncludedSection,
  cappedList,
  DEFAULT_COMMIT_TYPES,
  parseCommitlintRules,
  isConventionalHistory,
  compilePattern,
  buildConventionSection,
  buildRecentCommitsSection,
  buildUserInstructionsSection,
  buildCommitStyleSection,
  validateCommitSubject,
  inferHeaderMaxLength,
  DEFAULT_HEADER_MAX_LENGTH,
} from './features'
export type {
  ProposedCommit,
  FileSummary,
  FileSummaryInput,
  FileSummaryResult,
  SummaryGroupingInput,
  SummaryProgress,
  SummarizeOptions,
  CommitPlanRunners,
  SummaryCommitMessageInput,
  CommitMessageRunners,
  CommitMessageDraft,
  DailySummary,
  SummaryPrDescriptionInput,
  ChangeExplanationInput,
  ChangeExplanationFile,
  SummaryExplanationInput,
  SummaryExplanationScope,
  SummaryExplanationCommit,
  CodeReviewInput,
  CodeReviewScope,
  CodeReviewCoverage,
  BudgetedDiff,
  DiffFileSection,
  DiffFileTier,
  DiffTierOverrides,
  CommitRecomposeInput,
  CommitRecomposeSubject,
  DiffCoverage,
  DiffPromptSizing,
  CommitlintRules,
  CommitStyleContext,
  CommitValidation,
  CommitValidationProblem,
} from './features'
